

NUMPY PRACTICE



In [1]:
import numpy as np

Question 1

In [ ]:
#a

arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]

print(reversed_arr)

[5 4 6 3 2 1]


In [ ]:
#b
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])


flattened_array1 = array1.flatten()

print(flattened_array1)

[1 2 3 2 4 5 1 2 3]


In [ ]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])


flattened_array1 = array1.ravel()

print(flattened_array1)

[1 2 3 2 4 5 1 2 3]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])


comparison_result = arr1 == arr2

print(comparison_result)


[[ True  True]
 [ True  True]]


In [ ]:
#d
def most_frequent_value_and_indices(arr):
    unique_values, counts = np.unique(arr, return_counts=True)
    max_count = np.max(counts)
    most_frequent_values = unique_values[counts == max_count]
    indices = np.where(arr == most_frequent_values[0])[0]
    return most_frequent_values, indices

# Array x
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
most_frequent_x, indices_x = most_frequent_value_and_indices(x)
print("Array x:")
print("Most frequent value:", most_frequent_x)
print("Indices:", indices_x)

# Array y
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
most_frequent_y, indices_y = most_frequent_value_and_indices(y)
print("\nArray y:")
print("Most frequent value:", most_frequent_y)
print("Indices:", indices_y)


Array x:
Most frequent value: [1]
Indices: [0 5 7 8 9]

Array y:
Most frequent value: [1 3]
Indices: [0 1 2]


In [ ]:
#e
import numpy as np

gfg = np.array([[4, 1, 9], [12, 3, 1], [4, 5, 6]])

# i. Sum of all elements
sum_all_elements = np.sum(gfg)
print("Sum of all elements:", sum_all_elements)

# ii. Sum of all elements row-wise
sum_row_wise = np.sum(gfg, axis=1)
print("Sum of all elements row-wise:", sum_row_wise)

# iii. Sum of all elements column-wise
sum_column_wise = np.sum(gfg, axis=0)
print("Sum of all elements column-wise:", sum_column_wise)


Sum of all elements: 45
Sum of all elements row-wise: [14 16 15]
Sum of all elements column-wise: [20  9 16]


In [ ]:
#f
# Given matrix
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])

# i. Sum of diagonal elements
sum_diagonal = np.trace(n_array)
print("Sum of diagonal elements:", sum_diagonal)

# ii. Eigenvalues of matrix
eigenvalues, _ = np.linalg.eig(n_array)
print("Eigenvalues of the matrix:", eigenvalues)

# iii. Eigenvectors of matrix
_, eigenvectors = np.linalg.eig(n_array)
print("Eigenvectors of the matrix:")
for vector in eigenvectors.T:
    print(vector)

# iv. Inverse of matrix
try:
    inverse_matrix = np.linalg.inv(n_array)
    print("Inverse of the matrix:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("Matrix is singular, and its inverse does not exist.")

# v. Determinant of matrix
determinant = np.linalg.det(n_array)
print("Determinant of the matrix:", determinant)


Sum of diagonal elements: 176
Eigenvalues of the matrix: [98.16835147 28.097044   49.73460452]
Eigenvectors of the matrix:
[0.4574917  0.28447814 0.84248058]
[ 0.34637121 -0.72784061  0.59184038]
[-0.15017693 -0.4852124   0.8614034 ]
Inverse of the matrix:
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of the matrix: 137180.0000000001


In [ ]:
#g

p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])

# Matrix multiplication
result_matrix = np.dot(p, q)
print("Matrix multiplication result:")
print(result_matrix)

# Covariance between matrices
covariance_matrix = np.cov(p, q)
print("Covariance between matrices:")
print(covariance_matrix)


Matrix multiplication result:
[[16 19]
 [26 31]]
Covariance between matrices:
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [ ]:
#h

# Given matrices
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

# i. Inner product (Dot product)
inner_product = np.inner(x.flatten(), y.flatten())
print("Inner product:")
print(inner_product)

# ii. Outer product
outer_product = np.outer(x.flatten(), y.flatten())
print("\nOuter product:")
print(outer_product)

# iii. Cartesian product
cartesian_product = np.transpose([np.tile(x.flatten(), len(y.flatten())), np.repeat(y.flatten(), len(x.flatten()))])
print("\nCartesian product:")
print(cartesian_product)


Inner product:
79

Outer product:
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

Cartesian product:
[[ 2  1]
 [ 3  1]
 [ 4  1]
 [ 3  1]
 [ 2  1]
 [ 9  1]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2  0]
 [ 3  0]
 [ 4  0]
 [ 3  0]
 [ 2  0]
 [ 9  0]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2 10]
 [ 3 10]
 [ 4 10]
 [ 3 10]
 [ 2 10]
 [ 9 10]
 [ 2  3]
 [ 3  3]
 [ 4  3]
 [ 3  3]
 [ 2  3]
 [ 9  3]]


Question 2

In [ ]:
#a i
array = np.array([[1, -2, 3], [-4, 5, -6]])

# i. Element-wise absolute value
abs_array = np.abs(array)
print("Element-wise absolute value:")
print(abs_array)


Element-wise absolute value:
[[1 2 3]
 [4 5 6]]


In [ ]:
# ii
array = np.array([[1, -2, 3], [-4, 5, -6]])

# ii. Percentiles
percentiles_row = np.percentile(array, [25, 50, 75], axis=1)
percentiles_column = np.percentile(array, [25, 50, 75], axis=0)

print("Percentiles for each row:")
print(percentiles_row)

print("\nPercentiles for each column:")
print(percentiles_column)


Percentiles for each row:
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]

Percentiles for each column:
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]


In [ ]:
# iii. Mean, Median, and Standard Deviation
mean_flattened = np.mean(array.flatten())
median_flattened = np.median(array.flatten())
std_flattened = np.std(array.flatten())

mean_column = np.mean(array, axis=0)
median_column = np.median(array, axis=0)
std_column = np.std(array, axis=0)

mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)

print("Mean, Median, and Standard Deviation of the flattened array:")
print("Mean:", mean_flattened)
print("Median:", median_flattened)
print("Standard Deviation:", std_flattened)

print("\nMean, Median, and Standard Deviation of each column:")
print("Mean:", mean_column)
print("Median:", median_column)
print("Standard Deviation:", std_column)

print("\nMean, Median, and Standard Deviation of each row:")
print("Mean:", mean_row)
print("Median:", median_row)
print("Standard Deviation:", std_row)


Mean, Median, and Standard Deviation of the flattened array:
Mean: -0.5
Median: -0.5
Standard Deviation: 3.8622100754188224

Mean, Median, and Standard Deviation of each column:
Mean: [-1.5  1.5 -1.5]
Median: [-1.5  1.5 -1.5]
Standard Deviation: [2.5 3.5 4.5]

Mean, Median, and Standard Deviation of each row:
Mean: [ 0.66666667 -1.66666667]
Median: [ 1. -4.]
Standard Deviation: [2.05480467 4.78423336]


In [ ]:
#b
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

# Floor, Ceiling, and Truncated Value
floor_values = np.floor(a)
ceiling_values = np.ceil(a)
truncated_values = np.trunc(a)

# Rounded Values
rounded_values = np.round(a)

print("Floor values:", floor_values)
print("Ceiling values:", ceiling_values)
print("Truncated values:", truncated_values)
print("Rounded values:", rounded_values)


Floor values: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded values: [-2. -2. -0.  0.  2.  2.  3.]


Q3: Based on Searching and Sorting

In [ ]:
#a
array = np.array([10, 52, 62, 16, 16, 54, 453])

# i. Sorted array
sorted_array = np.sort(array)
print("Sorted array:")
print(sorted_array)

# ii. Indices of sorted array
sorted_indices = np.argsort(array)
print("\nIndices of sorted array:")
print(sorted_indices)

# iii. 4 smallest elements
smallest_elements = sorted_array[:4]
print("\n4 smallest elements:")
print(smallest_elements)

# iv. 5 largest elements
largest_elements = sorted_array[-5:]
print("\n5 largest elements:")
print(largest_elements)


Sorted array:
[ 10  16  16  52  54  62 453]

Indices of sorted array:
[0 3 4 1 5 2 6]

4 smallest elements:
[10 16 16 52]

5 largest elements:
[ 16  52  54  62 453]


In [ ]:
#b
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

# i. Integer elements only
integer_mask = array % 1 == 0
integer_elements = array[integer_mask]
print("Integer elements only:")
print(integer_elements)

# ii. Float elements only
float_mask = array % 1 != 0
float_elements = array[float_mask]
print("\nFloat elements only:")
print(float_elements)


Integer elements only:
[1. 2. 3. 2.]

Float elements only:
[1.2 2.2]


Question 4

In [ ]:
from PIL import Image
import numpy as np

def img_to_array(path):
    # Read the image
    img = Image.open(path)

    # Convert the image to grayscale or RGB mode based on its mode
    if img.mode == 'RGB':

        img_array = np.array(img)

        img_array_flattened = img_array.flatten()
    elif img.mode == 'L':

        img_array = np.array(img)
        # Flatten the 2D array to make it 1D
        img_array_flattened = img_array.flatten()
    else:
        raise ValueError("Unsupported image mode. Only RGB and grayscale images are supported.")

    # Save the flattened image array as a text file
    np.savetxt('image_data.txt', img_array_flattened, fmt='%d')

# Provide the path of the image file
image_path = '/colors.jfif'

# Call the function to save the image data as a text file
img_to_array(image_path)

# Load the text file containing the image data
loaded_img_array_flattened = np.loadtxt('image_data.txt', dtype=int)

# Reshape the flattened array to original shape (3D for RGB, 2D for grayscale)
img_shape = (loaded_img_array_flattened.shape[0] // 3, 3) if len(loaded_img_array_flattened.shape) == 1 else loaded_img_array_flattened.shape
loaded_img_array = loaded_img_array_flattened.reshape(img_shape)

# Display the loaded image data
print(loaded_img_array)


[[245 109   1]
 [250 109   3]
 [254 107   1]
 ...
 [ 40  47  57]
 [ 40  47  57]
 [ 40  47  57]]


In [ ]:
from PIL import Image
import numpy as np

def img_to_array(path):
    # Read the image
    img = Image.open(path)

    # Convert the image to grayscale or RGB mode based on its mode
    if img.mode == 'RGB':
        # Convert RGB image to NumPy array
        img_array = np.array(img)
        # Flatten the 3D array to make it 1D
        img_array_flattened = img_array.flatten()
    elif img.mode == 'L':
        # Convert grayscale image to NumPy array
        img_array = np.array(img)
        # Flatten the 2D array to make it 1D
        img_array_flattened = img_array.flatten()
    else:
        raise ValueError("Unsupported image mode. Only RGB and grayscale images are supported.")

    # Save the flattened image array as a text file
    np.savetxt('image_data.txt', img_array_flattened, fmt='%d')

image_path = '/blacknwhite.jfif'

# Call the function to save the image data as a text file
img_to_array(image_path)

# Load the text file containing the image data
loaded_img_array_flattened = np.loadtxt('image_data.txt', dtype=int)

# Reshape the flattened array to original shape (3D for RGB, 2D for grayscale)
img_shape = (loaded_img_array_flattened.shape[0] // 3, 3) if len(loaded_img_array_flattened.shape) == 1 else loaded_img_array_flattened.shape
loaded_img_array = loaded_img_array_flattened.reshape(img_shape)


print(loaded_img_array)


[[ 5  5  5]
 [ 5  5  5]
 [ 5  5  5]
 ...
 [24 24 24]
 [25 25 25]
 [25 25 25]]
